# Generated by Django 4.0.6 on 2022-08-04 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(default='익명의 집사', max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='profile/default.png', upload_to='profile/')),
            ],
        ),
    ]
