# Generated by Django 4.0.6 on 2022-08-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_count_users_roomcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='count_users',
            field=models.BigIntegerField(default=0),
        ),
    ]
