# Generated by Django 4.0.6 on 2022-08-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname_comment', to='common.profile'),
        ),
        migrations.AddField(
            model_name='boardcount',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
        migrations.AddField(
            model_name='board',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname_board', to='common.profile'),
        ),
        migrations.AddField(
            model_name='board',
            name='voter',
            field=models.ManyToManyField(related_name='vote_board', to='common.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
        migrations.AddField(
            model_name='answer',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname_answer', to='common.profile'),
        ),
    ]
