# Generated by Django 4.0.6 on 2022-08-03 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='voter',
            field=models.ManyToManyField(related_name='vote_board', to=settings.AUTH_USER_MODEL),
        ),
    ]
