# Generated by Django 4.0.6 on 2022-08-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_answer_nickname_alter_board_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='board',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
