# Generated by Django 4.0.6 on 2022-08-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_answer_nickname_alter_board_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='view_cnt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BoardCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
